# Generated by Django 4.2.1 on 2023-06-16 13:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='Ссылка на статью')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='static/img/', verbose_name='Фото статьи')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text', tinymce.models.HTMLField(verbose_name='Полный текст статьи')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
